name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: work-tuimer
            asset_name: work-tuimer-linux-x86_64

          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: work-tuimer
            asset_name: work-tuimer-macos-x86_64

          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: work-tuimer
            asset_name: work-tuimer-macos-aarch64

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: work-tuimer.exe
            asset_name: work-tuimer-windows-x86_64.exe

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          tag_name: ${{ github.ref_name }}
